# OIDs for snmpwalk
walk:
    - "IF-MIB::ifInOctets"
    - "IF-MIB::ifOutOctets"
    - "IF-MIB::ifSpeed"

get:
    - "LLDP-MIB::lldpRemPortId"
    - "LLDP-MIB::lldpRemPortDesc"
    - "LLDP-MIB::lldpRemSysName"
    - "LLDP-MIB::lldpLocSysName.0"
    - "LLDP-MIB::lldpLocChassisId.0"